### ISSUE TITLE
Bebop 1 compatibility

### ISSUE THREAD

**Issue by petetum** [Daggers/Bebop2Record2USBDrive#1]
To make it compatible with bebop 1 the following changes need to be made.

Add line:
BBDIR=$( if [ "$(gprop ro.hardware)" = "milosboard" ]; then echo Bebop_2; elif [ "$(gprop ro.hardware)" = "mykonos3board" ]; then echo Bebop_Drone; fi );

And replace the Bebop_2 with $BBDIR when re-mounting the USB drive.

**Comment by Daggers** [comment]
I`ve did it already and updated files in repository, but I used your method to detect drone version from old scripts.

**Comment by petetum** [comment]
Cool :)
