### ISSUE TITLE
lots of unnecessary feedback on terminal

### ISSUE THREAD

**Issue by petetum** [Daggers/Bebop2Record2USBDrive#2]
When running on terminal there are lots of unnecessary feedback from BLDC_Test_Bench

Add >/dev/null 2>&1 to end of all BLDC_Test_Bench lines.

**Comment by Daggers** [comment]
Are you sure? May be " >/dev/null &" ?
As example:
BB2: BLDC_Test_Bench -M 2 >/dev/null &
BB1: BLDC_Test_Bench -G 1 0 0 >/dev/null &

**Comment by petetum** [comment]
/ # BLDC_Test_Bench -G 1 0 0 >/dev/null &
comes back with:
/ # I2C_write_read() Frame Error. BLDC returned an empty message
  *** Warning: accessing to settings is forbidden when motors are spinning ! ***
MTB_BLDC_gpio_control1: field=0x1

/ # BLDC_Test_Bench -G 0 1 0 >/dev/null 2>&1
comes back with:
/ #

>/dev/null 2>&1 is redirect the output of your program to /dev/null. Include both the Standard Error and Standard Out

**Comment by Daggers** [comment]
ok, thanks!
I have all 5 scripts ready to final tests.
I`ll make this changes and will start test with different  firmwares. 
And ti will be another repository - https://github.com/Daggers/Bebop2CopyMoveRecord2USBDrive

**Comment by Daggers** [comment]
Ok, Copy\Move\Record scripts is ready. I`ve tested it on 4.2 and 4.0.4 firmwares. 
Next I will test it on 4.0.5, 4.0.6 and 42 again. 
And after all, when you test it too, we can publish it on Youtube.
