### ISSUE TITLE
can't umount /dev/sda1

### ISSUE THREAD

**Issue by petetum** [Daggers/Bebop2Record2USBDrive#3]
Unmount comes back with an error.

/ # umount /dev/sda1
umount: can't umount /dev/sda1: Invalid argument

To fix replace line with:
umount $( df | grep '/dev/sda1' | awk '{print $NF}' )

**Comment by Daggers** [comment]
Seems like you test ald scripts =)
It is new umount method used already:
USBDST=$(mount | grep sda1 | awk '{ print $3 }')
umount $USBDST
It works well on BB2 and must work on BB1. Check your scripts please.

**Comment by petetum** [comment]
works on BB1 v4.0.6
:)
