### ISSUE TITLE
shortpress 9

### ISSUE THREAD

**Issue by petetum** [Daggers/Bebop2Record2USBDrive#4]
on BB1 v4.0.6

/ # ./data/ftp/shortpress_9.sh
umount OK
mount: mounting /tmp/udev//dev/sda1 on /data/ftp/sda1 failed: No such file or directory
Can not mount!!!

You must create /data/ftp/sda1 before you can mount there.
OR
Mount to the original directory of the pendrive.

You could add a line to shortpress_8 to save the original location to a file in /tmp/
Like this:
echo $USBDST > /tmp/USBDST.data
Once you reboot the drone the file will disappear though..

Or to the /data/ftp/USBDST.data directory which has limited space but smaller files like this can be stored there.

And then read the file with shortpress_9 when re-mounting.

USBDST=$(cat /data/ftp/USBDST.data)
mount $USBSRC $USBDST
if [ $? -ne 0 ]; then
Fail
else
Success
rm /data/ftp/USBDST.data
fi

Or you can use different methods to find the original directory's name.
Like
for directory in $(find /data/ftp/ -maxdepth 1 -type d -regex ".*_[0-9][0-9][0-9]"); do
etc...

**Comment by Daggers** [comment]
I think it wil be enough to mount to /data/ftp/sda1
I will add mkdir before mount with check if it exist or not.

**Comment by Daggers** [comment]
Line 90 deleted, added:
	if [ -d /data/ftp/usbdrive ]; then
		mount $USBSRC /data/ftp/usbdrive
	else
		mkdir /data/ftp/usbdrive
		mount $USBSRC /data/ftp/usbdrive
	fi

Files updated in repository here and there =)

**Comment by petetum** [comment]
I didn't try the script but it should work with this mod.
